capture:
  colors_level:
    0:
    - 46
    - 46
    - 56
    1:
    - 79
    - 172
    - 254
    2:
    - 0
    - 242
    - 254
    3:
    - 76
    - 175
    - 80
    4:
    - 0
    - 230
    - 118
    5:
    - 255
    - 235
    - 59
    6:
    - 255
    - 152
    - 0
    7:
    - 255
    - 87
    - 34
    8:
    - 244
    - 67
    - 54
    9:
    - 213
    - 0
    - 249
    10:
    - 101
    - 31
    - 255
    11:
    - 55
    - 71
    - 79
  colors_x:
    '0':
    - 242
    - 227
    - 196
    '1':
    - 240
    - 240
    - 239
    '10':
    - 147
    - 104
    - 90
    '11':
    - 161
    - 123
    - 98
    '2':
    - 221
    - 217
    - 152
    '3':
    - 169
    - 217
    - 156
    '4':
    - 145
    - 208
    - 179
    '5':
    - 165
    - 174
    - 181
    '6':
    - 171
    - 122
    - 142
    '7':
    - 154
    - 100
    - 72
    '8':
    - 195
    - 109
    - 91
    '9':
    - 161
    - 128
    - 113
  crop_h: 770
  crop_w: 893
  crop_x: 65
  crop_y: 940
  empty_lum_threshold: 200
  empty_stddev_threshold: 50.0
  enabled: true
  mode: x
  port: 55781
  template_match_policy: ambiguous
  template_matching: true
